builds:
- env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  goos:
  - linux
  - darwin
archives:
- name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  format: binary
  wrap_in_directory: false
  files:
  - none*
changelog:
checksum:
  algorithm: sha1