
name: run-tests

on:
  workflow_call:
    outputs:
      pr_number:
        description: "The PR number"
        value: ${{ jobs.test.outputs.pr_number }}
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Go test
    outputs:
      pr_number: ${{ github.event.number }}
    steps:
    - uses: actions/setup-go@v6
      with:
        go-version: '1.25.1'
    - uses: actions/checkout@v5
    - run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo gpg --dearmor -o /usr/share/keyrings/cli.cloudfoundry.org.gpg
        echo "deb [signed-by=/usr/share/keyrings/cli.cloudfoundry.org.gpg] https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install -y cf8-cli
        make test
  call-dependabot-pr-workflow:
    needs: test
    if: ${{ success() && github.actor == 'dependabot[bot]' }}
    uses: cloudfoundry/cloud-service-broker/.github/workflows/dependabot-test.yml@main
    with:
      pr_number: ${{ github.event.number }}